SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'TBL_JAVADICT';
SELECT * FROM USER_CONS_COLUMNS WHERE TABLE_NAME = 'TBL_JAVADICT';

CREATE TABLE tbl_javadict2 AS SELECT * FROM TBL_JAVADICT;
SELECT * FROM TBL_JAVADICT2;

ALTER TABLE TBL_JAVADICT2 ADD CONSTRAINT pk_javadict2 PRIMARY KEY (idx);
ALTER TABLE TBL_JAVADICT2 ADD CONSTRAINT uq_english UNIQUE (ENGLISH);
ALTER TABLE TBL_JAVADICT2 ADD CONSTRAINT chk_stp CHECK (step BETWEEN '1' AND '3');

CREATE TABLE tbl_javadict3 AS SELECT * FROM TBL_JAVADICT;
SELECT * FROM TBL_JAVADICT3;

ALTER TABLE TBL_JAVADICT3 ADD CONSTRAINT pk_jacadict3 PRIMARY KEY (idx);
ALTER TABLE TBL_JAVADICT3 ADD CONSTRAINT uq_eng UNIQUE (ENGLISH);
ALTER TABLE TBL_JAVADICT3 ADD CONSTRAINT chk_stps CHECK (step BETWEEN '1' AND '3');

INSERT INTO TBL_JAVADICT3 (ENGLISH ,KOREAN, IDX,STEP) VALUES ('private','사적인',2,2);	
