SELECT COUNT (*) AS "전체갯수" FROM TBL_CAR_CO2;

SELECT COUNT(*) AS "볼보 갯수" FROM TBL_CAR_CO2 WHERE CAR = 'Volvo';
SELECT COUNT(*) AS "1000kg 미만 차량" FROM TBL_CAR_CO2 WHERE WEIGHT<1000;
SELECT AVG(CO2) AS "Co2 평균량" FROM TBL_CAR_CO2;

UPDATE TBL_CAR_CO2 SET WEIGHT = NULL WHERE MODEL = 'Lancer';

SELECT DISTINCT CAR FROM TBL_CAR_CO2;
SELECT COUNT(WEIGHT) AS "NULL 제외 갯수" FROM TBL_CAR_CO2;
SELECT WEIGHT FROM TBL_CAR_CO2;
SELECT AVG(WEIGHT) AS "NULL 제외 평균" FROM TBL_CAR_CO2;
SELECT NVL(WEIGHT,1000) FROM TBL_CAR_CO2;
SELECT ROUND(AVG(NVL(WEIGHT,1000)),0) FROM TBL_CAR_CO2;
SELECT ROUND(AVG(CO2),0) AS "CO2 정수",ROUND(AVG(NVL(WEIGHT,1000)),0) AS "차량 무게 평균" FROM TBL_CAR_CO2;
SELECT 
ROUND(AVG(CASE WHEN WEIGHT >= 1000 THEN WEIGHT END),0) AS "1000kg 이상 차량 무게 평균",
ROUND(AVG(CASE WHEN WEIGHT < 1000 THEN WEIGHT END),0) AS "1000kg 미만 차량 무게 평균" 
FROM TBL_CAR_CO2;

